# Project Workspace Switcher
#
# Generic Zsh helper for switching between configured workspaces and repo/path slots.
#
# Core commands:
#   pws             show active workspace
#   pws ls          list configured workspaces
#   pws pick        interactively select workspace with fzf
#   pws <name>      select workspace
#   pws add <name> [label]
#   pws rm <name> [--force]
#   pws path set <workspace> <repo> <path>
#   pws path rm <workspace> <repo>
#   pcd pick        interactively cd to repo/path with fzf
#   pcd <repo>      cd to repo/path in active workspace
#   pg pick         interactively cd to repo/path + git status with fzf
#   pg <repo>       cd to repo/path + git status
#   pag             git status for all repos/paths in active workspace
#
# Config:
#   Define PWS_WORKSPACES, PWS_REPOS and PWS_PATHS before sourcing this file,
#   or set PWS_CONFIG_FILE to a config file path.

typeset -g PWS_CONFIG_FILE="${PWS_CONFIG_FILE:-$HOME/.config/project-workspace-switcher/config.zsh}"
typeset -g PWS_DEFAULT_WORKSPACE="${PWS_DEFAULT_WORKSPACE:-main}"
typeset -g PWS_ACTIVE="${PWS_ACTIVE:-$PWS_DEFAULT_WORKSPACE}"
typeset -g PWS_FZF_BIN="${PWS_FZF_BIN:-fzf}"

typeset -ga PWS_WORKSPACES
typeset -ga PWS_REPOS
typeset -gA PWS_WORKSPACE_LABELS
typeset -gA PWS_REPO_LABELS
typeset -gA PWS_PATHS
typeset -g _PWS_MANAGED_BEGIN="# BEGIN PWS MANAGED REGISTRY"
typeset -g _PWS_MANAGED_END="# END PWS MANAGED REGISTRY"

unfunction pws pcd pg pag 2>/dev/null

_pws_load_config() {
  if [[ -f "$PWS_CONFIG_FILE" ]]; then
    source "$PWS_CONFIG_FILE"
  fi

  PWS_ACTIVE="${PWS_ACTIVE:-$PWS_DEFAULT_WORKSPACE}"
}

_pws_has_item() {
  local needle="$1"
  shift

  local item
  for item in "$@"; do
    [[ "$item" == "$needle" ]] && return 0
  done

  return 1
}

_pws_require_config() {
  if (( ${#PWS_WORKSPACES[@]} == 0 )); then
    print -u2 -- "No workspaces configured. Define PWS_WORKSPACES in your config."
    return 1
  fi

  if (( ${#PWS_REPOS[@]} == 0 )); then
    print -u2 -- "No repo/path slots configured. Define PWS_REPOS in your config."
    return 1
  fi
}

_pws_validate_registry_name() {
  local kind="$1"
  local name="$2"

  if [[ -z "$name" ]]; then
    print -u2 -- "$kind is required."
    return 1
  fi

  if [[ ! "$name" =~ '^[A-Za-z0-9._-]+$' ]]; then
    print -u2 -- "Invalid $kind: $name"
    print -u2 -- "Use only letters, numbers, dot, underscore and hyphen."
    return 1
  fi
}

_pws_quote_zsh() {
  local value="$1"
  print -r -- "${(qqq)value}"
}

_pws_managed_registry_block() {
  local workspace key

  print -r -- "$_PWS_MANAGED_BEGIN"
  print -r -- "# Generated by pws registry commands. Edit outside this block for hand-managed settings."
  print -r -- "typeset -ga PWS_WORKSPACES=("
  for workspace in "${PWS_WORKSPACES[@]}"; do
    print -r -- "  $(_pws_quote_zsh "$workspace")"
  done
  print -r -- ")"
  print
  print -r -- "typeset -gA PWS_WORKSPACE_LABELS=("
  for workspace in "${PWS_WORKSPACES[@]}"; do
    if [[ -n "${PWS_WORKSPACE_LABELS[$workspace]+set}" ]]; then
      print -r -- "  [$(_pws_quote_zsh "$workspace")]=$(_pws_quote_zsh "${PWS_WORKSPACE_LABELS[$workspace]}")"
    fi
  done
  print -r -- ")"
  print
  print -r -- "typeset -gA PWS_PATHS=("
  for key in "${(@ok)PWS_PATHS}"; do
    print -r -- "  [$(_pws_quote_zsh "$key")]=$(_pws_quote_zsh "${PWS_PATHS[$key]}")"
  done
  print -r -- ")"
  print -r -- "$_PWS_MANAGED_END"
}

_pws_write_managed_registry() {
  local config_dir tmp line in_block replaced
  local -a lines block_lines output

  config_dir="${PWS_CONFIG_FILE:h}"
  if [[ -n "$config_dir" && "$config_dir" != "." ]]; then
    command mkdir -p -- "$config_dir" || return 1
  fi

  block_lines=("${(@f)$(_pws_managed_registry_block)}")
  lines=()
  if [[ -f "$PWS_CONFIG_FILE" ]]; then
    lines=("${(@f)$(<"$PWS_CONFIG_FILE")}")
  fi

  output=()
  in_block=0
  replaced=0

  for line in "${lines[@]}"; do
    if [[ "$line" == "$_PWS_MANAGED_BEGIN" ]]; then
      if (( ! replaced )); then
        output+=("${block_lines[@]}")
        replaced=1
      fi
      in_block=1
      continue
    fi

    if (( in_block )) && [[ "$line" == "$_PWS_MANAGED_END" ]]; then
      in_block=0
      continue
    fi

    (( in_block )) && continue
    output+=("$line")
  done

  if (( ! replaced )); then
    (( ${#output[@]} > 0 )) && output+=("")
    output+=("${block_lines[@]}")
  fi

  tmp="${PWS_CONFIG_FILE}.tmp.$$"
  {
    for line in "${output[@]}"; do
      print -r -- "$line"
    done
  } >"$tmp" || return 1

  command mv -- "$tmp" "$PWS_CONFIG_FILE"
}

_pws_reload_config_after_write() {
  _pws_load_config
}

_pws_select_fallback_active() {
  if _pws_workspace_exists "$PWS_ACTIVE"; then
    return
  fi

  if _pws_workspace_exists "$PWS_DEFAULT_WORKSPACE"; then
    typeset -g PWS_ACTIVE="$PWS_DEFAULT_WORKSPACE"
    return
  fi

  if (( ${#PWS_WORKSPACES[@]} > 0 )); then
    typeset -g PWS_ACTIVE="${PWS_WORKSPACES[1]}"
    return
  fi

  typeset -g PWS_ACTIVE="$PWS_DEFAULT_WORKSPACE"
}

_pws_registry_add_workspace() {
  local workspace="$1"
  shift
  local label="${*:-$workspace}"

  _pws_validate_registry_name "workspace name" "$workspace" || return 1

  if ! _pws_workspace_exists "$workspace"; then
    PWS_WORKSPACES+=("$workspace")
  fi

  PWS_WORKSPACE_LABELS[$workspace]="$label"
  _pws_write_managed_registry || return 1
  _pws_reload_config_after_write
  print -r -- "Updated workspace registry: added $workspace"
}

_pws_registry_remove_workspace() {
  local workspace=""
  local force=0
  local arg item key
  local -a next_workspaces

  for arg in "$@"; do
    case "$arg" in
      --force)
        force=1
        ;;
      *)
        if [[ -n "$workspace" ]]; then
          print -u2 -- "Usage: pws rm <workspace> [--force]"
          return 1
        fi
        workspace="$arg"
        ;;
    esac
  done

  _pws_validate_registry_name "workspace name" "$workspace" || return 1

  if ! _pws_workspace_exists "$workspace"; then
    print -u2 -- "Unknown workspace: $workspace"
    return 1
  fi

  if [[ "$workspace" == "$PWS_ACTIVE" && "$force" -ne 1 ]]; then
    print -u2 -- "Refusing to remove active workspace: $workspace"
    print -u2 -- "Run: pws rm $workspace --force"
    return 1
  fi

  next_workspaces=()
  for item in "${PWS_WORKSPACES[@]}"; do
    [[ "$item" == "$workspace" ]] && continue
    next_workspaces+=("$item")
  done
  PWS_WORKSPACES=("${next_workspaces[@]}")

  unset "PWS_WORKSPACE_LABELS[$workspace]"
  for key in "${(@k)PWS_PATHS}"; do
    [[ "$key" == "$workspace:"* ]] && unset "PWS_PATHS[$key]"
  done

  _pws_write_managed_registry || return 1
  _pws_reload_config_after_write
  _pws_select_fallback_active
  print -r -- "Updated workspace registry: removed $workspace"
}

_pws_registry_path_set() {
  local workspace="$1"
  local repo="$2"
  local repo_dir="$3"
  local key

  if [[ $# -ne 3 ]]; then
    print -u2 -- "Usage: pws path set <workspace> <repo> <path>"
    return 1
  fi

  _pws_validate_registry_name "workspace name" "$workspace" || return 1
  _pws_validate_registry_name "repo/path slot name" "$repo" || return 1

  if ! _pws_workspace_exists "$workspace"; then
    print -u2 -- "Unknown workspace: $workspace"
    return 1
  fi

  if ! _pws_repo_exists "$repo"; then
    print -u2 -- "Unknown repo/path slot: $repo"
    print -u2 -- "Configured slots: ${PWS_REPOS[*]}"
    return 1
  fi

  key=$(_pws_path_key "$workspace" "$repo")
  PWS_PATHS[$key]="$repo_dir"
  _pws_write_managed_registry || return 1
  _pws_reload_config_after_write
  print -r -- "Updated workspace registry: set $workspace / $repo"
}

_pws_registry_path_remove() {
  local workspace="$1"
  local repo="$2"
  local key

  if [[ $# -ne 2 ]]; then
    print -u2 -- "Usage: pws path rm <workspace> <repo>"
    return 1
  fi

  _pws_validate_registry_name "workspace name" "$workspace" || return 1
  _pws_validate_registry_name "repo/path slot name" "$repo" || return 1

  key=$(_pws_path_key "$workspace" "$repo")
  unset "PWS_PATHS[$key]"
  _pws_write_managed_registry || return 1
  _pws_reload_config_after_write
  print -r -- "Updated workspace registry: removed $workspace / $repo"
}

_pws_workspace_exists() {
  _pws_has_item "$1" "${PWS_WORKSPACES[@]}"
}

_pws_repo_exists() {
  _pws_has_item "$1" "${PWS_REPOS[@]}"
}

_pws_require_fzf() {
  if [[ -z "$PWS_FZF_BIN" ]] || ! command -v -- "$PWS_FZF_BIN" >/dev/null 2>&1; then
    print -u2 -- "fzf is not installed. Install fzf or use pws ls / pws <workspace> / pcd <repo>."
    return 1
  fi
}

_pws_workspace_label() {
  local workspace="$1"
  print -r -- "${PWS_WORKSPACE_LABELS[$workspace]:-$workspace}"
}

_pws_repo_label() {
  local repo="$1"
  print -r -- "${PWS_REPO_LABELS[$repo]:-$repo}"
}

_pws_path_key() {
  local workspace="$1"
  local repo="$2"
  print -r -- "${workspace}:${repo}"
}

_pws_repo_dir() {
  local workspace="$1"
  local repo="$2"
  local key

  key=$(_pws_path_key "$workspace" "$repo")
  print -r -- "${PWS_PATHS[$key]}"
}

_pws_print_current() {
  _pws_require_config || return 1

  if ! _pws_workspace_exists "$PWS_ACTIVE"; then
    print -u2 -- "Active workspace is not configured: $PWS_ACTIVE"
    return 1
  fi

  local repo repo_dir label
  print -r -- "Active workspace: $PWS_ACTIVE ($(_pws_workspace_label "$PWS_ACTIVE"))"

  for repo in "${PWS_REPOS[@]}"; do
    repo_dir=$(_pws_repo_dir "$PWS_ACTIVE" "$repo")
    label=$(_pws_repo_label "$repo")
    print -r -- "  $repo  $label  $repo_dir"
  done
}

_pws_print_list() {
  _pws_require_config || return 1

  local workspace marker
  print -r -- "Available workspaces:"

  for workspace in "${PWS_WORKSPACES[@]}"; do
    marker=" "
    [[ "$workspace" == "$PWS_ACTIVE" ]] && marker="*"
    print -r -- " $marker $workspace  $(_pws_workspace_label "$workspace")"
  done

  print
  print -r -- "Active workspace: $PWS_ACTIVE"
}

_pws_pick_workspace() {
  _pws_require_fzf || return 1

  local workspace selection

  selection=$(
    for workspace in "${PWS_WORKSPACES[@]}"; do
      print -r -- "${workspace}	$(_pws_workspace_label "$workspace")"
    done | command "$PWS_FZF_BIN"
  ) || return 1

  [[ -n "$selection" ]] || return 1

  workspace="${selection%%	*}"
  pws "$workspace"
}

_pws_pick_repo() {
  local action="$1"

  if ! _pws_workspace_exists "$PWS_ACTIVE"; then
    print -u2 -- "Active workspace is not configured: $PWS_ACTIVE"
    return 1
  fi

  _pws_require_fzf || return 1

  local repo repo_dir selection

  selection=$(
    for repo in "${PWS_REPOS[@]}"; do
      repo_dir=$(_pws_repo_dir "$PWS_ACTIVE" "$repo")
      print -r -- "${repo}	$(_pws_repo_label "$repo")	${repo_dir}"
    done | command "$PWS_FZF_BIN"
  ) || return 1

  [[ -n "$selection" ]] || return 1

  repo="${selection%%	*}"
  "$action" "$repo"
}

pws() {
  _pws_load_config

  if [[ $# -eq 0 ]]; then
    _pws_require_config || return 1
    _pws_print_current
    return
  fi

  case "$1" in
    ls|--list|-l)
      _pws_require_config || return 1
      _pws_print_list
      return
      ;;
    pick)
      _pws_require_config || return 1
      _pws_pick_workspace
      return
      ;;
    add)
      shift
      if [[ $# -lt 1 ]]; then
        print -u2 -- "Usage: pws add <workspace> [label]"
        return 1
      fi
      _pws_registry_add_workspace "$@"
      return
      ;;
    rm|remove)
      shift
      _pws_registry_remove_workspace "$@"
      return
      ;;
    path)
      shift
      case "$1" in
        set)
          shift
          _pws_registry_path_set "$@"
          return
          ;;
        rm|remove)
          shift
          _pws_registry_path_remove "$@"
          return
          ;;
        *)
          print -u2 -- "Usage: pws path set <workspace> <repo> <path>"
          print -u2 -- "   or: pws path rm <workspace> <repo>"
          return 1
          ;;
      esac
      ;;
    help|--help|-h)
      print -r -- "Usage:"
      print -r -- "  pws              show active workspace"
      print -r -- "  pws ls           list configured workspaces"
      print -r -- "  pws pick         interactively select workspace with fzf"
      print -r -- "  pws add <workspace> [label]"
      print -r -- "  pws rm <workspace> [--force]"
      print -r -- "  pws remove <workspace> [--force]"
      print -r -- "  pws path set <workspace> <repo> <path>"
      print -r -- "  pws path rm <workspace> <repo>"
      print -r -- "  pws <workspace>  select workspace"
      print -r -- "  pcd pick         interactively cd to repo/path with fzf"
      print -r -- "  pcd <repo>       cd to repo/path in active workspace"
      print -r -- "  pg pick          interactively cd + git status with fzf"
      print -r -- "  pg <repo>        cd to repo/path + git status"
      print -r -- "  pag              git status for all repos/paths in active workspace"
      return
      ;;
  esac

  _pws_require_config || return 1

  if ! _pws_workspace_exists "$1"; then
    print -u2 -- "Unknown workspace: $1"
    print -u2 -- "Run: pws ls"
    return 1
  fi

  typeset -g PWS_ACTIVE="$1"
  _pws_print_current
}

pcd() {
  _pws_load_config
  _pws_require_config || return 1

  local repo="$1"
  local repo_dir

  if [[ -z "$repo" ]]; then
    print -u2 -- "Usage: pcd <repo>"
    return 1
  fi

  if [[ "$repo" == "pick" ]]; then
    _pws_pick_repo pcd
    return
  fi

  if ! _pws_workspace_exists "$PWS_ACTIVE"; then
    print -u2 -- "Active workspace is not configured: $PWS_ACTIVE"
    return 1
  fi

  if ! _pws_repo_exists "$repo"; then
    print -u2 -- "Unknown repo/path slot: $repo"
    print -u2 -- "Configured slots: ${PWS_REPOS[*]}"
    return 1
  fi

  repo_dir=$(_pws_repo_dir "$PWS_ACTIVE" "$repo")

  if [[ -z "$repo_dir" ]]; then
    print -u2 -- "No path configured for workspace/repo: $PWS_ACTIVE / $repo"
    return 1
  fi

  if [[ ! -d "$repo_dir" ]]; then
    print -u2 -- "Missing directory: $repo_dir"
    return 1
  fi

  builtin cd "$repo_dir"
}

pg() {
  local repo="$1"
  local branch

  if [[ -z "$repo" ]]; then
    print -u2 -- "Usage: pg <repo>"
    return 1
  fi

  if [[ "$repo" == "pick" ]]; then
    _pws_load_config
    _pws_require_config || return 1
    _pws_pick_repo pg
    return
  fi

  pcd "$repo" || return 1

  branch=$(command git branch --show-current 2>/dev/null)

  if [[ -n "$branch" ]]; then
    print -P "%~(${branch})"
  else
    print -P "%~"
  fi

  command git status
}

pag() {
  _pws_load_config
  _pws_require_config || return 1

  if ! _pws_workspace_exists "$PWS_ACTIVE"; then
    print -u2 -- "Active workspace is not configured: $PWS_ACTIVE"
    return 1
  fi

  local repo repo_dir branch label

  print -r -- "Active workspace: $PWS_ACTIVE ($(_pws_workspace_label "$PWS_ACTIVE"))"

  for repo in "${PWS_REPOS[@]}"; do
    repo_dir=$(_pws_repo_dir "$PWS_ACTIVE" "$repo")
    label=$(_pws_repo_label "$repo")

    print
    print -r -- "$repo  $label"
    print -r -- "$repo_dir"

    if [[ -z "$repo_dir" ]]; then
      print -r -- "No path configured."
      continue
    fi

    if [[ ! -d "$repo_dir" ]]; then
      print -r -- "Missing directory."
      continue
    fi

    branch=$(command git -C "$repo_dir" branch --show-current 2>/dev/null)

    if [[ -n "$branch" ]]; then
      print -r -- "branch: $branch"
    fi

    command git -C "$repo_dir" status
  done
}

_pws_load_config
